name: Test React App
on: push
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Test app
        run: npm run build
  test:
    runs-on: ubuntu-latest
    need: build
    steps:
      # - name: Get repo code
        # uses: actions/checkout@v3
      # - name: Install dependecies
        # run: npm ci
      - name: Test app
        run: npm run test
  deploy:
    runs-on: ubuntu-latest
    need: test
    steps:
      - name: Test app
        run: npm run test
