name: Test React App
on: push
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Build app
        run: npm run build
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get repo code
        uses: actions/checkout@v3
        # как добиться, чтобы npm ci работал для нескольких джобов один раз ???
      - name: Install dependecies
        run: npm ci
      - name: Test app
        run: npm run test
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy app
        run: echo deploy ...
